# Generated by Django 3.2.19 on 2023-09-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_householdmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='householdmember',
            old_name='Household',
            new_name='household',
        ),
    ]
