# Generated by Django 3.2.19 on 2023-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_household_rent_is_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='creator_has_paid_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='has_paid_rent',
            field=models.BooleanField(default=False),
        ),
    ]
